#!/bin/sh
#################################################
#
# Description: 查看平台应用进程状态参数配置
# Usage: 自动执行
# Author: xupiao
# Date: 2015-12-1
# Version: v2.1
#
#################################################

function usage() {
   pluginDir=$VOICE_FRW_HOME/bin/plugins/status
   if [ -d $pluginDir ]; then
      echo "Subcommand: status"
      echo "Extended: true"
      echo "Desc: `cat $pluginDir/desc.txt`"
      if [ -f $pluginDir/usage.txt ]; then
         echo "`cat $pluginDir/usage.txt`"
      fi
   fi
}

###参数个数检查###
if [ $# -lt 1 ]; then
   usage
   exit 1
fi
app=$1

###VOICE_APP_PID###
export VOICE_APP_PID=$VOICE_FRW_HOME/etc/pids/voice."$app".pid

