#!/bin/sh
#################################################
#
# Description: 重启平台应用
# Usage: restart <app> <vmid>
# Author: xupiao
# Date: 2015-11-12
# Version: v2.0
#
#################################################

function usage() {
   pluginDir=$VOICE_EXTEND_HOME/bin/plugins/restart
   if [ -d $pluginDir ]; then
      echo "Subcommand: restart"
      echo "Extended: true"
      echo "Desc: `cat $pluginDir/desc.txt`"
      if [ -f $pluginDir/usage.txt ]; then
         echo "`cat $pluginDir/usage.txt`"
      fi
   fi
}

###参数个数检查###
if [ $# -lt 1 ]; then
   usage
   exit 1
fi
app=$1

###先停止###
sh -e $VOICE_FRW_HOME/sbin/core/voice stop $app

###后启动###
sh -e $VOICE_FRW_HOME/sbin/core/voice start $app

exit 0

